### ISSUE TITLE
Fuglanesøk takler ikke æ, ø eller å

### ISSUE THREAD

**Issue by boyebn** [Orakeltjenesten/scripts#2]
Ser ut som det ikke funger så bra med æ, ø og å i alfred-workflowen :(
Ser også at workflow-biblioteket til python ikke støtter python3, så det var ikke en quick-fix. Antagelig er det bare å loke rundt med `.encode('utf-8')` og `.decode('utf-8')`

<img width="540" alt="skjermbilde 2015-10-22 kl 14 37 08" src="https://cloud.githubusercontent.com/assets/6630430/10665285/6ef431fa-78ca-11e5-9b08-dee205b756ea.png">

**Comment by JakobGM** [comment]
Jeg har lagt inn en pullrequest for å fikse dette her:
https://github.com/Orakeltjenesten/scripts/pull/1

Dette skal fikse feilen. Får vente på at den blir godkjent.

**Comment by Lemonous** [comment]
Lukker denne siden #1 er blitt merget :P
